# Generated by Django 4.1.3 on 2022-11-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.CharField(max_length=100, verbose_name='Название')),
                ('article_content', models.TextField(verbose_name='Контент')),
                ('article_date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
