# Generated by Django 4.1.3 on 2022-11-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_username',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
